import React from "react";
import type { Metadata } from "next";
import Image from "next/image";
import signup_banner from "@/public/signup-banner.png";
import logo from "@/public/linktree-logo.png";

export const metadata: Metadata = {
  title: "Log in or Sign Up | Linktree",
  description: "Generated by create next app",
};

const Signup = () => {
  return (
    <>
      <div className="flex ">
        <div className="flex-1 ">
          <div className="flex items-center py-12 px-12">
            <h1 className="text-3xl font-medium">Linktree</h1>
            <Image src={logo} height={25} width={19} alt="linktree-logo" />
          </div>
          <div className="border-2 border-red-500">
            <div className="flex flex-col items-center gap-4">
              <h1 className="text-5xl font-bold">Join Linktree</h1>
              <p>Sign up for free!</p>
            </div>
          </div>
        </div>
        <div
          className=""
          style={{
            display: "flex",
            alignItems: "center",
            height: "100vh",
            overflow: "hidden",
          }}
        >
          <Image
            src={signup_banner}
            height={960}
            width={1000}
            alt="signup-banner"
            objectFit="contain"
            priority
          />
        </div>
      </div>
    </>
  );
};

export default Signup;
